### ISSUE TITLE
0223_Week 01 一维数据结构的更多理解

### ISSUE THREAD

**Issue by 0291** [algorithm005-class02/algorithm005-class02#61]
学习心得：
一：掌握了查找Java数据结构及其API的方法；数组，链表，在源码中：栈是一个类，队列是一个接口，优先队列是一个类，双端队列是一个接口。
二：掌握这些一维数据结构的使用和适用的场景和环境，以及各自的特点。
三：优先队列的插入操作是O(1)的，取出操作是log(n)的，变慢了，因为是按照一定的优先级取出。
四：关于Queue和Deque源码的阅读分析:
Queue源码分析：
继承了集合的顶层Collection<E>接口，提供的API接口有
Boolean add(E e)：加入元素
Boolean offer(E e)：在没有超出空间限制的情况下插入元素
E remove()：移除队列的头元素
E poll():删除头节点
E element():
    返回当前队列的头节点；
    若队列为空将抛出：NoSuchElementException
E peek():查看当前队列的头元素。
PriorityQueue源码分析：
（1）继承了AbstractQueue的接口，以及实现了serializable接口，
（2）其中peek,clear,offer，poll等操作有利用到数组这样的数据结果为装载数据的原型载体
（3）实现了三种：无参，传递初始容量initialCapaicty，以比较器对象为参数的
等多种构造方法；
（4）通过调用比较器comparator规则，实现对PriorityDeque的初始化（元素vip定级）
（5）源码中实现了Iterator迭代器类的next()方法，以及hasNext()方法等
（6）其中实现提供了如下的API接口：
grow方法：扩充底层实现的数组的容量
add(E e)；返回调用的是自身的offer(E e)方法；
offer():实现插入元素
poll():弹出一个元素
peek():查看队列头部的元素，返回的是 {return (E) queue[0];}
indexof():以数组为遍历对象，返回队列中的元素在数组中
remove():先是判断当前元素的下标是否越界，然后再移除指定位置的元素
。。。。。
五：关于利用新的API重写ppt上的代码：
import java.util.Deque;
import java.util.LinkedList;

public class Deque_realize{
    public static void main(String[] args) {
        Deque_realize de=new Deque_realize();
        de.new_api_deque();

    }
    public void new_api_deque(){
        Deque<String> deque =new LinkedList<String>();
        deque.addLast("a");
        deque.addLast("b");
        deque.addLast("c");
        System.out.println(deque);

        String str=deque.peek();
        System.out.println(str);
        System.out.println(deque);
        
        while(deque.size()>0){
            System.out.println(deque.pop());
        }
        System.out.println(deque);
    }
}

**Comment by shushuiu** [comment]
nice

**Comment by Hypon-liu** [comment]
poll():是弹出队列头节点，并删除元素
peek():是查看队列头节点，不删除元素
这两个对比记忆，就不容易混淆了，这一点超哥视频中有讲到

**Comment by congve1** [comment]
底层数据结构实际上是个堆，这个感觉可以加上，在将 Collection 转为优先队列时，会调用 heapify()这函数，保证优先级

**Comment by 0291** [comment]
> nice

thanks

**Comment by 0291** [comment]
> 底层数据结构实际上是个堆，这个感觉可以加上，在将 Collection 转为优先队列时，会调用 heapify()这函数，保证优先级
