### ISSUE TITLE
【0111_Week 07】 学习总结

### ISSUE THREAD

**Issue by bingliuys** [algorithm005-class02/algorithm005-class02#906]
第7周学习了BitWise、 BloomFilter、LRUCache、Sort Algorithm，对各知识点进行整理和一些见解：
# BitWise:

- 6种运算符(|，&，~，^，>>，<<)
- 多种常用的操作（如：指定位置的位运算、判断奇偶 等）
- 在软件世界里面一切都是用二进制来表示，在机器里面如果直接操作二进制，速度相对是比较快，一些算法题如果能转换成二进制再进行求解，通常能节省空间和时间。

# BloomFilter:
- 一种空间效率极高的概率型算法和数据结构，主要用来判断一个元素是否在集合中存在。使用于超大的集合判断。
- 抽象原理：
需要一个超大的bit数组，把元素进行不同hash后（例如：3次），得到一个数组下标，此时修改bit数据对应的下标内的值为‘1’。如果需要判断是否存在，只需要判断对应的下标位置是否都是‘1’。

# LRUCache：
- least recently used，针对cache设计的一种特殊数据结果用来解决cache不够时，清除长时间不使用的缓存。
- 数据结构是：hashmap+deque，查询的time complexty 是 O(1)

# Sort Algorithm：
排序大类有 比较排序和非比较排序
按time complexty划分，O(N^2),O(logN),O(N)

- 比较-》O(N^2): selection sort\ insertion sort\bubble sort
- 比较-》O(logN): merge sort\quick sort\heap sort
- 非比较-》O(N): counting sort\bucket sort\ radix sort

- 比较排序：
有两类，一类是线性的对比，另一类是树结构进行对比。

- 非比较排序原理：
我理解核心思想与hash有点类似。
原理：
先定义一个有序的数组，把需要排序的元素存储到数组的下标上，这样自然就排好序了。
或者对排序的元素进行一定规则（如高低位）进行存储，再分别排序。

**Comment by llkongl** [comment]
记得比较全面。
有一点记错了：排序算法那里是NlogN

**Comment by sk-yimo** [comment]
全面的总结

**Comment by redhare-ma** [comment]
学习了

**Comment by rateyu** [comment]
不错，可以补充写核心代码

**Comment by bingliuys** [comment]
> 记得比较全面。
> 有一点记错了：排序算法那里是NlogN

NlogN 是没错了。前面的N没写，我认为也是正确的。因为前面的常量可以省略。
